### ISSUE TITLE
Crashlytics 3

### ISSUE THREAD

**Issue by prsolucoes** [zergtmn/Fabric#18]
Hi,

The pod was updated to version 3?

Thanks.

**Comment by bestwnh** [comment]
+1 hope it can be done soon.

**Comment by vmalov** [comment]
+

**Comment by Alexs1987** [comment]
Really hoping it can be done soon!!!

**Comment by Panajev** [comment]
I think it is very important to keep up to date with Fabric and Crashlytics changes, please stay on top of this :+1:

**Comment by cmicali** [comment]
+1 would be very helpful

**Comment by zergtmn** [comment]
Hey guys, I'm currently preparing an update. Couldn't do that at work.

**Comment by cmicali** [comment]
Thanks!

**Comment by zergtmn** [comment]
I've just pushed v1.3.0 of the pod containing the latest versions of Crashlytics, TwitterKit, Digits and MoPub. Digits is under Fabric/Twitter subspec for now because I couldn't separate it properly without causing conflicts with TwitterKit.
Also important note: If you add podspec but don't `#import` the corresponding framework your project might fail to build.

**Comment by vmalov** [comment]
thx!
