### ISSUE TITLE
Deprecate in favor of the new official pod

### ISSUE THREAD

**Issue by bpoplauschi** [zergtmn/Fabric#30]
Fabric recently released Crashlytics, TwitterKit, Digits and Fabric as official pods on CocoaPods Trunk: https://cocoapods.org/owners/7558

I am in progress of deprecating CrashlyticsFramework in favour of their official pods. Would you like doing the same for this pod? See details here: https://github.com/bpoplauschi/CrashlyticsFramework/issues/31

**Comment by zergtmn** [comment]
Sure.

**Comment by AliSoftware** [comment]
I'm not sure that's applicable for @zergtmn because (for now at least) they didn't publish a specific pod for Fabric, but rather became owner of @zergtmn 's pod (see https://cocoapods.org/pods/Fabric : that still points to this repo but Fabric is in the list of Maintainers now)

(In contrast, for Crashlytics, they published a "Crashlytics" pod that is different from @bpoplauschi 's "CrashlyticsFramework" pod)

**Comment by bpoplauschi** [comment]
They just removed some of the specs from this Fabric repo. https://github.com/CocoaPods/Specs/pull/13313. I think this link: https://cocoapods.org/pods/Fabric will be fixed soon, as the Twitter folks asked about that. It's clear to me that they want people to use their official specs and therefore we should help as we can by migrating our users to them.

**Comment by zergtmn** [comment]
I believe the docs will update automatically to point to the official pod once they cleanup CocoaPods/Specs repo from 1.3.x versions.
