### ISSUE TITLE
CoccoaPods 0.36.0.rc.1 Fails with transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by savagegus** [zergtmn/Fabric#8]
The breaking change is described here: https://github.com/CocoaPods/CocoaPods/issues/2926. More details can be found here: http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/.

I'm not sure there is much to be done about it reading over the issue. The error I see when I try to run pod install is:

```
[!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/XXX/XXXApp/Pods/Fabric/Fabric.framework and /Users/XXX/XXXApp/Pods/Fabric/Crashlytics.framework)
```

**Comment by zergtmn** [comment]
The discussion regarding that change is still going on https://github.com/CocoaPods/CocoaPods/issues/3194 Let's see what we will have for 0.36 final.
I can't even push an update with 0.36.0.rc.1. Will stick to 0.35 for a while.

**Comment by jshier** [comment]
Still broken with 0.36.0. Perhaps having them as sibling frameworks rather than the sub frameworks depending on Core. After all, they'll all be linked with the app in the end, so the dependency may not be necessary.

**Comment by zergtmn** [comment]
@jshier thanks for idea. I've removed the dependencies between subspecs in v1.2. As a downside it is now required to specify 'Fabric' or 'Fabric/Core' in Podfile. Try it out to see if it resolves issues in your case.

**Comment by jshier** [comment]
What if, instead, the subspecs merely include both the Fabric and subspec framework directly. I believe that would still work around the 0.36 change while removing the requirement that Fabric be included directly. I also think that the default spec should just be all of the frameworks rather than just the Fabric framework, as the Fabric framework by itself doesn't do much, AFAIK.
